[tool.poetry]
name = "haruka-bot"
version = "1.1.1-alpha.5"
description = "Push dynamics and live informations from bilibili to QQ. Based on nonebot2."
authors = ["SK-415 <2967923486@qq.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/SK-415/HarukaBot"
repository = "https://github.com/SK-415/HarukaBot/tree/master/src/plugins/haruka_bot"
documentation = "https://github.com/SK-415/HarukaBot#readme"
keywords = ["nonebot", "nonebot2", "qqbot", "bilibili", "bot"]
packages = [
    { include = "haruka_bot/*.py", from = "./src/plugins/"},
    { include = "haruka_bot/cli/*.py", from = "./src/plugins/"}
]

[tool.poetry.scripts]
hb = 'haruka_bot.cli.__main__:main'

[tool.poetry.dependencies]
python = "^3.8"
qrcode = {extras = ["pil"], version = "^6.1"}
pyppeteer = "^0.2.2"
tinydb = "^4.3.0"
packaging = "^20.7"
nonebot-plugin-apscheduler = "^0.1.0"
pydantic = "^1.7.3"
nonebot2 = "^2.0.0-alpha.7"

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.4"
nb-cli = "^0.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
