[tool.poetry]
name = "haruka-bot"
version = "1.3.5"
description = "Push dynamics and live informations from bilibili to QQ. Based on nonebot2."
authors = ["SK-415 <2967923486@qq.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/SK-415/HarukaBot"
repository = "https://github.com/SK-415/HarukaBot/tree/master/src/plugins/haruka_bot"
documentation = "https://github.com/SK-415/HarukaBot#readme"
keywords = ["nonebot", "nonebot2", "qqbot", "bilibili", "bot"]
packages = [
    { include = "haruka_bot", from = "./src/plugins/"}
]

[tool.poetry.scripts]
hb = 'haruka_bot.__main__:main'

[tool.poetry.dependencies]
python = "^3.8"
packaging = "^20.9"
appdirs = "^1.4.4"
click = "^8.0.1"
httpx = "^0.18.2"
nonebot-adapter-onebot = "^2.0.0-beta.1"
nonebot-plugin-apscheduler = "^0.1.2"
nonebot2 = "^2.0.0-beta.2"
pillow = "^8.2.0"
playwright = "^1.15.0"
bilireq = {extras = ["qrcode"], version = "^0.1.0-alpha.0"}
pydantic = "^1.8.2"
python-dotenv = "^0.17.1"
rsa = "^4.7.2"
tortoise-orm = {extras = ["asyncpg"], version = "^0.18.1"}

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.4"
black = "^21.9b0"
flake8 = "^4.0.1"

[nonebot.plugins]
plugins = []
plugin_dirs = ["src/plugins"]

# [[tool.poetry.source]]
# name = "tsinghua"
# url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
# default = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
